/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HomeSection = {
  _type: "homeSection";
  sectionType?:
    | "trustedBrands"
    | "story"
    | "credibility"
    | "founderTeaser"
    | "services"
    | "mediaHub"
    | "cprSpotlight"
    | "mediaDesk"
    | "awardsSpotlight"
    | "brands"
    | "resourcesMembership"
    | "newsletter"
    | "contact";
  enabled?: boolean;
  internalNote?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        blank?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Stat = {
  _type: "stat";
  value?: string;
  numericValue?: number;
  suffix?: string;
  label?: string;
  note?: string;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
  external?: boolean;
  style?: "dark" | "pink" | "light" | "white" | "media";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type VideoGallery = {
  _id: string;
  _type: "videoGallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  intro?: string;
  videos?: Array<{
    heading?: string;
    url?: string;
    caption?: string;
    _key: string;
  }>;
  order?: number;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Toolkit = {
  _id: string;
  _type: "toolkit";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  type?: string;
  description?: string;
  access?: "free" | "members" | "paid" | "comingSoon";
  coverStyle?: "cream" | "pink" | "dark";
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  downloadFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  externalUrl?: string;
  order?: number;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  type?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  href?: string;
  ctaLabel?: string;
  external?: boolean;
  order?: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  category?: string;
  format?:
    | "article"
    | "interview"
    | "video"
    | "podcast"
    | "news"
    | "opinion"
    | "report";
  publishedAt?: string;
  readingTime?: string;
  author?: AuthorReference;
  body?: PortableText;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  externalVideoUrl?: string;
  featured?: boolean;
  tags?: Array<string>;
  relatedService?: ServiceReference;
  relatedArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type MembershipPage = {
  _id: string;
  _type: "membershipPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  comingSoonLabel?: string;
  heroTitle?: string;
  heroAccent?: string;
  intro?: string;
  benefitsEyebrow?: string;
  benefitsHeading?: string;
  benefitsIntro?: string;
  benefits?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type DiamondAwards = {
  _id: string;
  _type: "diamondAwards";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eventName?: string;
  date?: string;
  venue?: string;
  location?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  historyImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  missionImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  whyDubaiImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  sponsorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  experienceImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  contactImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  history?: PortableText;
  mission?: PortableText;
  missionPoints?: Array<string>;
  audience?: Array<string>;
  eventExperience?: Array<string>;
  sponsorBenefits?: Array<string>;
  sponsorshipPackages?: Array<{
    tier?: string;
    name?: string;
    description?: string;
    features?: Array<string>;
    _key: string;
  }>;
  contactEmail?: string;
  contactPhoneUae?: string;
  contactPhoneUk?: string;
  seo?: Seo;
};

export type VideoPage = {
  _id: string;
  _type: "videoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroAccent?: string;
  intro?: string;
  ctaEyebrow?: string;
  ctaHeading?: string;
  ctaText?: string;
  ctaButtonLabel?: string;
  ctaButtonHref?: string;
  seo?: Seo;
};

export type MediaHubPage = {
  _id: string;
  _type: "mediaHubPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroAccent?: string;
  intro?: string;
  ctaEyebrow?: string;
  ctaHeading?: string;
  ctaText?: string;
  ctaButtonLabel?: string;
  ctaButtonHref?: string;
  seo?: Seo;
};

export type MediaDesk = {
  _id: string;
  _type: "mediaDesk";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline?: string;
  intro?: string;
  requestTypes?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  futureResources?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Founder = {
  _id: string;
  _type: "founder";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: string;
  intro?: string;
  body?: PortableText;
  belief?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  statsNote?: string;
  publications?: Array<string>;
  roles?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroTitle?: string;
  heroAccent?: string;
  intro?: string;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  evolutionEyebrow?: string;
  evolutionHeading?: string;
  evolutionBody?: PortableText;
  quote?: string;
  closingNote?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  principlesEyebrow?: string;
  principlesHeading?: string;
  principlesIntro?: string;
  principles?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type CosmeticPrPage = {
  _id: string;
  _type: "cosmeticPrPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitle?: string;
  heroAccent?: string;
  heroIntro?: string;
  heroBody?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroCaption?: string;
  heroCaptionMeta?: string;
  identityStrip?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
  storyEyebrow?: string;
  storySideHeading?: string;
  storySideText?: string;
  storyHeading?: string;
  storyAccent?: string;
  storyBody?: PortableText;
  capabilitiesEyebrow?: string;
  capabilitiesNote?: string;
  capabilitiesHeading?: string;
  capabilities?: Array<{
    title?: string;
    description?: string;
    _key: string;
  }>;
  casesEyebrow?: string;
  casesHeading?: string;
  cases?: Array<{
    label?: string;
    title?: string;
    description?: string;
    tags?: string;
    _key: string;
  }>;
  testimonialsEyebrow?: string;
  testimonialsHeading?: string;
  testimonials?: Array<{
    name?: string;
    quote?: string;
    _key: string;
  }>;
  publicationsEyebrow?: string;
  publicationsHeading?: string;
  publicationsIntro?: string;
  publications?: Array<string>;
  summaryEyebrow?: string;
  summaryHeading?: string;
  summaryBody?: PortableText;
  summaryPoints?: Array<{
    label?: string;
    text?: string;
    _key: string;
  }>;
  newsletterEyebrow?: string;
  newsletterHeading?: string;
  newsletterText?: string;
  seo?: Seo;
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type ToolkitReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "toolkit";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrowLeft?: string;
  heroEyebrowRight?: string;
  heroTitleBefore?: string;
  heroTitleAccent?: string;
  heroIdentity?: string;
  heroSummary?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImageCaption?: string;
  heroImageMeta?: string;
  heroFilm?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  heroVideoUrl?: string;
  heroFilmBadge?: string;
  founderFilm?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  storyHeading?: string;
  storyOpening?: string;
  storyBody?: PortableText;
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  credibilityFacts?: Array<{
    label?: string;
    title?: string;
    _key: string;
  }>;
  publications?: Array<string>;
  clientLogos?: Array<{
    name?: string;
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  featuredArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  featuredServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  featuredBrands?: Array<
    {
      _key: string;
    } & BrandReference
  >;
  featuredToolkits?: Array<
    {
      _key: string;
    } & ToolkitReference
  >;
  latestRail?: Array<{
    label?: string;
    title?: string;
    actionLabel?: string;
    href?: string;
    _key: string;
  }>;
  brandRail?: Array<{
    label?: string;
    title?: string;
    description?: string;
    href?: string;
    _key: string;
  }>;
  resourceTiles?: Array<{
    tag?: string;
    title?: string;
    actionLabel?: string;
    href?: string;
    _key: string;
  }>;
  cprEyebrow?: string;
  cprHeading?: string;
  cprAccent?: string;
  cprIntro?: string;
  cprStatusChips?: Array<string>;
  cprCards?: Array<{
    label?: string;
    title?: string;
    text?: string;
    ctaLabel?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  sections?: Array<
    {
      _key: string;
    } & HomeSection
  >;
  seo?: Seo;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  about?: {
    eyebrow?: string;
    heading?: string;
    text?: string;
    ctaLabel?: string;
    ctaHref?: string;
    links?: Array<{
      label?: string;
      page?:
        | "/"
        | "/about"
        | "/cosmetic-pr"
        | "/about/founder"
        | "/services"
        | "/media-hub"
        | "/diamond-awards"
        | "/our-brands"
        | "/toolkits"
        | "/membership"
        | "/media-desk"
        | "/contact";
      service?: ServiceReference;
      externalUrl?: string;
      _type: "menuLink";
      _key: string;
    }>;
  };
  services?: {
    eyebrow?: string;
    heading?: string;
    text?: string;
    ctaLabel?: string;
    ctaHref?: string;
    links?: Array<{
      label?: string;
      page?:
        | "/"
        | "/about"
        | "/cosmetic-pr"
        | "/about/founder"
        | "/services"
        | "/media-hub"
        | "/diamond-awards"
        | "/our-brands"
        | "/toolkits"
        | "/membership"
        | "/media-desk"
        | "/contact";
      service?: ServiceReference;
      externalUrl?: string;
      _type: "menuLink";
      _key: string;
    }>;
  };
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  eyebrow?: string;
  intro?: string;
  listDescription?: string;
  listCta?: string;
  detailIntro?: string;
  body?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  outcomes?: Array<string>;
  deliverables?: Array<string>;
  order?: number;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  email?: string;
  phone?: string;
  locations?: string;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
  legalLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | HomeSection
  | SanityImageAssetReference
  | PortableText
  | Stat
  | Link
  | Seo
  | VideoGallery
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | Toolkit
  | Brand
  | AuthorReference
  | ServiceReference
  | ArticleReference
  | Article
  | Author
  | MembershipPage
  | DiamondAwards
  | VideoPage
  | MediaHubPage
  | MediaDesk
  | Founder
  | AboutPage
  | CosmeticPrPage
  | BrandReference
  | ToolkitReference
  | Homepage
  | Navigation
  | Service
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  title, tagline, description, email, phone, locations, socialLinks, legalLinks,  "logo": logo{..., "asset": asset->{_id,_ref,url}}, seo}
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  tagline: string | null;
  description: string | null;
  email: string | null;
  phone: string | null;
  locations: string | null;
  socialLinks: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }> | null;
  legalLinks: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
  logo: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage"][0]{  heroTitle, heroAccent, intro, stats,  evolutionEyebrow, evolutionHeading, evolutionBody, quote, closingNote,  principlesEyebrow, principlesHeading, principlesIntro, principles, seo,  "image": image{..., "asset": asset->{_id,_ref,url}}}
export type ABOUT_PAGE_QUERY_RESULT = {
  heroTitle: string | null;
  heroAccent: string | null;
  intro: string | null;
  stats: Array<
    {
      _key: string;
    } & Stat
  > | null;
  evolutionEyebrow: string | null;
  evolutionHeading: string | null;
  evolutionBody: PortableText | null;
  quote: string | null;
  closingNote: string | null;
  principlesEyebrow: string | null;
  principlesHeading: string | null;
  principlesIntro: string | null;
  principles: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  seo: Seo | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: COSMETIC_PR_PAGE_QUERY
// Query: *[_type == "cosmeticPrPage"][0]{  heroEyebrow, heroTitle, heroAccent, heroIntro, heroBody,  "heroImage": heroImage{..., "asset": asset->{_id,_ref,url}},  heroCaption, heroCaptionMeta, identityStrip,  storyEyebrow, storySideHeading, storySideText, storyHeading, storyAccent, storyBody,  capabilitiesEyebrow, capabilitiesNote, capabilitiesHeading, capabilities,  casesEyebrow, casesHeading, cases,  testimonialsEyebrow, testimonialsHeading, testimonials,  publicationsEyebrow, publicationsHeading, publicationsIntro, publications,  summaryEyebrow, summaryHeading, summaryBody, summaryPoints,  newsletterEyebrow, newsletterHeading, newsletterText, seo}
export type COSMETIC_PR_PAGE_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroTitle: string | null;
  heroAccent: string | null;
  heroIntro: string | null;
  heroBody: string | null;
  heroImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroCaption: string | null;
  heroCaptionMeta: string | null;
  identityStrip: Array<{
    label?: string;
    value?: string;
    _key: string;
  }> | null;
  storyEyebrow: string | null;
  storySideHeading: string | null;
  storySideText: string | null;
  storyHeading: string | null;
  storyAccent: string | null;
  storyBody: PortableText | null;
  capabilitiesEyebrow: string | null;
  capabilitiesNote: string | null;
  capabilitiesHeading: string | null;
  capabilities: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  casesEyebrow: string | null;
  casesHeading: string | null;
  cases: Array<{
    label?: string;
    title?: string;
    description?: string;
    tags?: string;
    _key: string;
  }> | null;
  testimonialsEyebrow: string | null;
  testimonialsHeading: string | null;
  testimonials: Array<{
    name?: string;
    quote?: string;
    _key: string;
  }> | null;
  publicationsEyebrow: string | null;
  publicationsHeading: string | null;
  publicationsIntro: string | null;
  publications: Array<string> | null;
  summaryEyebrow: string | null;
  summaryHeading: string | null;
  summaryBody: PortableText | null;
  summaryPoints: Array<{
    label?: string;
    text?: string;
    _key: string;
  }> | null;
  newsletterEyebrow: string | null;
  newsletterHeading: string | null;
  newsletterText: string | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBERSHIP_PAGE_QUERY
// Query: *[_type == "membershipPage"][0]{  comingSoonLabel, heroTitle, heroAccent, intro,  benefitsEyebrow, benefitsHeading, benefitsIntro, benefits, seo}
export type MEMBERSHIP_PAGE_QUERY_RESULT = {
  comingSoonLabel: string | null;
  heroTitle: string | null;
  heroAccent: string | null;
  intro: string | null;
  benefitsEyebrow: string | null;
  benefitsHeading: string | null;
  benefitsIntro: string | null;
  benefits: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0]{  heroEyebrowLeft, heroEyebrowRight, heroTitleBefore, heroTitleAccent,  heroIdentity, heroSummary, "heroImage": heroImage{..., "asset": asset->{_id,_ref,url}},  heroImageCaption, heroImageMeta,  "heroFilm": heroFilm[]{..., "asset": asset->{_id,_ref,url}},  heroVideoUrl, heroFilmBadge,  storyHeading, storyOpening, storyBody,  stats, credibilityFacts, publications,  clientLogos[]{name, "image": logo{..., "asset": asset->{_id,_ref,url}}},  latestRail, brandRail, resourceTiles,  "founderFilm": founderFilm[]{..., "asset": asset->{_id,_ref,url}},  cprEyebrow, cprHeading, cprAccent, cprIntro, cprStatusChips,  cprCards[]{label, title, text, ctaLabel, "image": image{..., "asset": asset->{_id,_ref,url}}},  sections[]{sectionType,enabled}, seo,  featuredArticles[]->{_id,title,"slug":slug.current,excerpt,category,format,publishedAt,readingTime,featured,    "image": image{..., "asset": asset->{_id,_ref,url}}, externalVideoUrl,    author->{name,"slug":slug.current,role,bio,"image":image{...,"asset":asset->{_id,_ref,url}}}  },  featuredServices[]->{_id,title,"slug":slug.current,eyebrow,intro,body,outcomes,deliverables,order,    "image":image{...,"asset":asset->{_id,_ref,url}}},  featuredBrands[]->{title,"slug":slug.current,type,description,href,external,order,    "image":image{...,"asset":asset->{_id,_ref,url}}},  featuredToolkits[]->{title,"slug":slug.current,type,description,access,coverStyle,externalUrl,    "fileUrl":downloadFile.asset->url}}
export type HOMEPAGE_QUERY_RESULT = {
  heroEyebrowLeft: string | null;
  heroEyebrowRight: string | null;
  heroTitleBefore: string | null;
  heroTitleAccent: string | null;
  heroIdentity: string | null;
  heroSummary: string | null;
  heroImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroImageCaption: string | null;
  heroImageMeta: string | null;
  heroFilm: Array<{
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  heroVideoUrl: string | null;
  heroFilmBadge: string | null;
  storyHeading: string | null;
  storyOpening: string | null;
  storyBody: PortableText | null;
  stats: Array<
    {
      _key: string;
    } & Stat
  > | null;
  credibilityFacts: Array<{
    label?: string;
    title?: string;
    _key: string;
  }> | null;
  publications: Array<string> | null;
  clientLogos: Array<{
    name: string | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  latestRail: Array<{
    label?: string;
    title?: string;
    actionLabel?: string;
    href?: string;
    _key: string;
  }> | null;
  brandRail: Array<{
    label?: string;
    title?: string;
    description?: string;
    href?: string;
    _key: string;
  }> | null;
  resourceTiles: Array<{
    tag?: string;
    title?: string;
    actionLabel?: string;
    href?: string;
    _key: string;
  }> | null;
  founderFilm: Array<{
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  cprEyebrow: string | null;
  cprHeading: string | null;
  cprAccent: string | null;
  cprIntro: string | null;
  cprStatusChips: Array<string> | null;
  cprCards: Array<{
    label: string | null;
    title: string | null;
    text: string | null;
    ctaLabel: string | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  sections: Array<{
    sectionType:
      | "awardsSpotlight"
      | "brands"
      | "contact"
      | "cprSpotlight"
      | "credibility"
      | "founderTeaser"
      | "mediaDesk"
      | "mediaHub"
      | "newsletter"
      | "resourcesMembership"
      | "services"
      | "story"
      | "trustedBrands"
      | null;
    enabled: boolean | null;
  }> | null;
  seo: Seo | null;
  featuredArticles: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    excerpt: string | null;
    category: string | null;
    format:
      | "article"
      | "interview"
      | "news"
      | "opinion"
      | "podcast"
      | "report"
      | "video"
      | null;
    publishedAt: string | null;
    readingTime: string | null;
    featured: boolean | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    externalVideoUrl: string | null;
    author: {
      name: string | null;
      slug: string | null;
      role: string | null;
      bio: string | null;
      image: {
        asset: {
          _id: string;
          _ref: null;
          url: string | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
    } | null;
  }> | null;
  featuredServices: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    eyebrow: string | null;
    intro: string | null;
    body: string | null;
    outcomes: Array<string> | null;
    deliverables: Array<string> | null;
    order: number | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  featuredBrands: Array<{
    title: string | null;
    slug: string | null;
    type: string | null;
    description: string | null;
    href: string | null;
    external: boolean | null;
    order: number | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
  featuredToolkits: Array<{
    title: string | null;
    slug: string | null;
    type: string | null;
    description: string | null;
    access: "comingSoon" | "free" | "members" | "paid" | null;
    coverStyle: "cream" | "dark" | "pink" | null;
    externalUrl: string | null;
    fileUrl: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(order asc, title asc){  _id,title,"slug":slug.current,eyebrow,intro,listDescription,listCta,detailIntro,body,outcomes,deliverables,order,seo,  "image":image{...,"asset":asset->{_id,_ref,url}}}
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  eyebrow: string | null;
  intro: string | null;
  listDescription: string | null;
  listCta: string | null;
  detailIntro: string | null;
  body: string | null;
  outcomes: Array<string> | null;
  deliverables: Array<string> | null;
  order: number | null;
  seo: Seo | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{  _id,title,"slug":slug.current,eyebrow,intro,listDescription,listCta,detailIntro,body,outcomes,deliverables,order,seo,  "image":image{...,"asset":asset->{_id,_ref,url}}}
export type SERVICE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  eyebrow: string | null;
  intro: string | null;
  listDescription: string | null;
  listCta: string | null;
  detailIntro: string | null;
  body: string | null;
  outcomes: Array<string> | null;
  deliverables: Array<string> | null;
  order: number | null;
  seo: Seo | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && defined(slug.current)] | order(publishedAt desc){  _id,title,"slug":slug.current,excerpt,category,format,publishedAt,readingTime,featured,externalVideoUrl,seo,  "image":image{...,"asset":asset->{_id,_ref,url}},  author->{name,"slug":slug.current,role,bio,"image":image{...,"asset":asset->{_id,_ref,url}}}}
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  format:
    | "article"
    | "interview"
    | "news"
    | "opinion"
    | "podcast"
    | "report"
    | "video"
    | null;
  publishedAt: string | null;
  readingTime: string | null;
  featured: boolean | null;
  externalVideoUrl: string | null;
  seo: Seo | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    name: string | null;
    slug: string | null;
    role: string | null;
    bio: string | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{  _id,title,"slug":slug.current,excerpt,category,format,publishedAt,readingTime,featured,externalVideoUrl,body,tags,seo,  "image":image{...,"asset":asset->{_id,_ref,url}},  author->{name,"slug":slug.current,role,bio,"image":image{...,"asset":asset->{_id,_ref,url}}},  relatedService->{title,"slug":slug.current},  relatedArticles[]->{_id,title,"slug":slug.current,excerpt,category,format,publishedAt,    "image":image{...,"asset":asset->{_id,_ref,url}}}}
export type ARTICLE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  category: string | null;
  format:
    | "article"
    | "interview"
    | "news"
    | "opinion"
    | "podcast"
    | "report"
    | "video"
    | null;
  publishedAt: string | null;
  readingTime: string | null;
  featured: boolean | null;
  externalVideoUrl: string | null;
  body: PortableText | null;
  tags: Array<string> | null;
  seo: Seo | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    name: string | null;
    slug: string | null;
    role: string | null;
    bio: string | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
  relatedService: {
    title: string | null;
    slug: string | null;
  } | null;
  relatedArticles: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    excerpt: string | null;
    category: string | null;
    format:
      | "article"
      | "interview"
      | "news"
      | "opinion"
      | "podcast"
      | "report"
      | "video"
      | null;
    publishedAt: string | null;
    image: {
      asset: {
        _id: string;
        _ref: null;
        url: string | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: BRANDS_QUERY
// Query: *[_type == "brand"] | order(order asc, title asc){  title,"slug":slug.current,type,description,href,external,ctaLabel,order,  "image":image{...,"asset":asset->{_id,_ref,url}}}
export type BRANDS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  type: string | null;
  description: string | null;
  href: string | null;
  external: boolean | null;
  ctaLabel: string | null;
  order: number | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: TOOLKITS_QUERY
// Query: *[_type == "toolkit"] | order(order asc, title asc){  title,"slug":slug.current,type,description,access,coverStyle,externalUrl,  "fileUrl":downloadFile.asset->url,  "coverImage":coverImage{...,"asset":asset->{_id,_ref,url}}}
export type TOOLKITS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  type: string | null;
  description: string | null;
  access: "comingSoon" | "free" | "members" | "paid" | null;
  coverStyle: "cream" | "dark" | "pink" | null;
  externalUrl: string | null;
  fileUrl: string | null;
  coverImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: FOUNDER_QUERY
// Query: *[_type == "founder"][0]{  name,headline,intro,body,belief,stats,statsNote,publications,roles,seo,  "image":image{...,"asset":asset->{_id,_ref,url}}}
export type FOUNDER_QUERY_RESULT = {
  name: string | null;
  headline: string | null;
  intro: string | null;
  body: PortableText | null;
  belief: string | null;
  stats: Array<
    {
      _key: string;
    } & Stat
  > | null;
  statsNote: string | null;
  publications: Array<string> | null;
  roles: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  seo: Seo | null;
  image: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MEDIA_DESK_QUERY
// Query: *[_type == "mediaDesk"][0]{headline,intro,requestTypes,futureResources,seo}
export type MEDIA_DESK_QUERY_RESULT = {
  headline: string | null;
  intro: string | null;
  requestTypes: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  futureResources: Array<{
    title?: string;
    description?: string;
    _key: string;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MEDIA_HUB_QUERY
// Query: *[_type == "mediaHubPage"][0]{heroTitle,heroAccent,intro,ctaEyebrow,ctaHeading,ctaText,ctaButtonLabel,ctaButtonHref,seo}
export type MEDIA_HUB_QUERY_RESULT = {
  heroTitle: string | null;
  heroAccent: string | null;
  intro: string | null;
  ctaEyebrow: string | null;
  ctaHeading: string | null;
  ctaText: string | null;
  ctaButtonLabel: string | null;
  ctaButtonHref: string | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: VIDEO_PAGE_QUERY
// Query: *[_type == "videoPage"][0]{heroTitle,heroAccent,intro,ctaEyebrow,ctaHeading,ctaText,ctaButtonLabel,ctaButtonHref,seo}
export type VIDEO_PAGE_QUERY_RESULT = {
  heroTitle: string | null;
  heroAccent: string | null;
  intro: string | null;
  ctaEyebrow: string | null;
  ctaHeading: string | null;
  ctaText: string | null;
  ctaButtonLabel: string | null;
  ctaButtonHref: string | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"][0]{  about{eyebrow, heading, text, ctaLabel, ctaHref, links[]{label, page, externalUrl, service->{title, "slug": slug.current}}},  services{eyebrow, heading, text, ctaLabel, ctaHref, links[]{label, page, externalUrl, service->{title, "slug": slug.current}}}}
export type NAVIGATION_QUERY_RESULT = {
  about: {
    eyebrow: string | null;
    heading: string | null;
    text: string | null;
    ctaLabel: string | null;
    ctaHref: string | null;
    links: Array<{
      label: string | null;
      page:
        | "/"
        | "/about"
        | "/about/founder"
        | "/contact"
        | "/cosmetic-pr"
        | "/diamond-awards"
        | "/media-desk"
        | "/media-hub"
        | "/membership"
        | "/our-brands"
        | "/services"
        | "/toolkits"
        | null;
      externalUrl: string | null;
      service: {
        title: string | null;
        slug: string | null;
      } | null;
    }> | null;
  } | null;
  services: {
    eyebrow: string | null;
    heading: string | null;
    text: string | null;
    ctaLabel: string | null;
    ctaHref: string | null;
    links: Array<{
      label: string | null;
      page:
        | "/"
        | "/about"
        | "/about/founder"
        | "/contact"
        | "/cosmetic-pr"
        | "/diamond-awards"
        | "/media-desk"
        | "/media-hub"
        | "/membership"
        | "/our-brands"
        | "/services"
        | "/toolkits"
        | null;
      externalUrl: string | null;
      service: {
        title: string | null;
        slug: string | null;
      } | null;
    }> | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: VIDEOS_QUERY
// Query: *[_type == "videoGallery"] | order(coalesce(order, 999) asc, title asc){  title, "slug": slug.current, category, intro, order,  "poster": poster{..., "asset": asset->{_id,_ref,url}},  videos[]{heading, url, caption}}
export type VIDEOS_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
  category: string | null;
  intro: string | null;
  order: number | null;
  poster: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  videos: Array<{
    heading: string | null;
    url: string | null;
    caption: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: VIDEO_QUERY
// Query: *[_type == "videoGallery" && slug.current == $slug][0]{  title, "slug": slug.current, category, intro, order,  "poster": poster{..., "asset": asset->{_id,_ref,url}},  videos[]{heading, url, caption}, seo}
export type VIDEO_QUERY_RESULT = {
  title: string | null;
  slug: string | null;
  category: string | null;
  intro: string | null;
  order: number | null;
  poster: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  videos: Array<{
    heading: string | null;
    url: string | null;
    caption: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: DIAMOND_AWARDS_QUERY
// Query: *[_type == "diamondAwards"][0]{  eventName,date,venue,location,history,mission,missionPoints,audience,eventExperience,sponsorBenefits,  sponsorshipPackages,contactEmail,contactPhoneUae,contactPhoneUk,seo,  "heroImage":heroImage{...,"asset":asset->{_id,_ref,url}},  "historyImage":historyImage{...,"asset":asset->{_id,_ref,url}},  "missionImage":missionImage{...,"asset":asset->{_id,_ref,url}},  "whyDubaiImage":whyDubaiImage{...,"asset":asset->{_id,_ref,url}},  "sponsorImage":sponsorImage{...,"asset":asset->{_id,_ref,url}},  "experienceImage":experienceImage{...,"asset":asset->{_id,_ref,url}},  "contactImage":contactImage{...,"asset":asset->{_id,_ref,url}}}
export type DIAMOND_AWARDS_QUERY_RESULT = {
  eventName: string | null;
  date: string | null;
  venue: string | null;
  location: string | null;
  history: PortableText | null;
  mission: PortableText | null;
  missionPoints: Array<string> | null;
  audience: Array<string> | null;
  eventExperience: Array<string> | null;
  sponsorBenefits: Array<string> | null;
  sponsorshipPackages: Array<{
    tier?: string;
    name?: string;
    description?: string;
    features?: Array<string>;
    _key: string;
  }> | null;
  contactEmail: string | null;
  contactPhoneUae: string | null;
  contactPhoneUk: string | null;
  seo: Seo | null;
  heroImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  historyImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  missionImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  whyDubaiImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  sponsorImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  experienceImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  contactImage: {
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  title, tagline, description, email, phone, locations, socialLinks, legalLinks,\n  "logo": logo{..., "asset": asset->{_id,_ref,url}}, seo\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "aboutPage"][0]{\n  heroTitle, heroAccent, intro, stats,\n  evolutionEyebrow, evolutionHeading, evolutionBody, quote, closingNote,\n  principlesEyebrow, principlesHeading, principlesIntro, principles, seo,\n  "image": image{..., "asset": asset->{_id,_ref,url}}\n}': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "cosmeticPrPage"][0]{\n  heroEyebrow, heroTitle, heroAccent, heroIntro, heroBody,\n  "heroImage": heroImage{..., "asset": asset->{_id,_ref,url}},\n  heroCaption, heroCaptionMeta, identityStrip,\n  storyEyebrow, storySideHeading, storySideText, storyHeading, storyAccent, storyBody,\n  capabilitiesEyebrow, capabilitiesNote, capabilitiesHeading, capabilities,\n  casesEyebrow, casesHeading, cases,\n  testimonialsEyebrow, testimonialsHeading, testimonials,\n  publicationsEyebrow, publicationsHeading, publicationsIntro, publications,\n  summaryEyebrow, summaryHeading, summaryBody, summaryPoints,\n  newsletterEyebrow, newsletterHeading, newsletterText, seo\n}': COSMETIC_PR_PAGE_QUERY_RESULT;
    '*[_type == "membershipPage"][0]{\n  comingSoonLabel, heroTitle, heroAccent, intro,\n  benefitsEyebrow, benefitsHeading, benefitsIntro, benefits, seo\n}': MEMBERSHIP_PAGE_QUERY_RESULT;
    '*[_type == "homepage"][0]{\n  heroEyebrowLeft, heroEyebrowRight, heroTitleBefore, heroTitleAccent,\n  heroIdentity, heroSummary, "heroImage": heroImage{..., "asset": asset->{_id,_ref,url}},\n  heroImageCaption, heroImageMeta,\n  "heroFilm": heroFilm[]{..., "asset": asset->{_id,_ref,url}},\n  heroVideoUrl, heroFilmBadge,\n  storyHeading, storyOpening, storyBody,\n  stats, credibilityFacts, publications,\n  clientLogos[]{name, "image": logo{..., "asset": asset->{_id,_ref,url}}},\n  latestRail, brandRail, resourceTiles,\n  "founderFilm": founderFilm[]{..., "asset": asset->{_id,_ref,url}},\n  cprEyebrow, cprHeading, cprAccent, cprIntro, cprStatusChips,\n  cprCards[]{label, title, text, ctaLabel, "image": image{..., "asset": asset->{_id,_ref,url}}},\n  sections[]{sectionType,enabled}, seo,\n  featuredArticles[]->{_id,title,"slug":slug.current,excerpt,category,format,publishedAt,readingTime,featured,\n    "image": image{..., "asset": asset->{_id,_ref,url}}, externalVideoUrl,\n    author->{name,"slug":slug.current,role,bio,"image":image{...,"asset":asset->{_id,_ref,url}}}\n  },\n  featuredServices[]->{_id,title,"slug":slug.current,eyebrow,intro,body,outcomes,deliverables,order,\n    "image":image{...,"asset":asset->{_id,_ref,url}}},\n  featuredBrands[]->{title,"slug":slug.current,type,description,href,external,order,\n    "image":image{...,"asset":asset->{_id,_ref,url}}},\n  featuredToolkits[]->{title,"slug":slug.current,type,description,access,coverStyle,externalUrl,\n    "fileUrl":downloadFile.asset->url}\n}': HOMEPAGE_QUERY_RESULT;
    '*[_type == "service"] | order(order asc, title asc){\n  _id,title,"slug":slug.current,eyebrow,intro,listDescription,listCta,detailIntro,body,outcomes,deliverables,order,seo,\n  "image":image{...,"asset":asset->{_id,_ref,url}}\n}': SERVICES_QUERY_RESULT;
    '*[_type == "service" && slug.current == $slug][0]{\n  _id,title,"slug":slug.current,eyebrow,intro,listDescription,listCta,detailIntro,body,outcomes,deliverables,order,seo,\n  "image":image{...,"asset":asset->{_id,_ref,url}}\n}': SERVICE_QUERY_RESULT;
    '*[_type == "article" && defined(slug.current)] | order(publishedAt desc){\n  _id,title,"slug":slug.current,excerpt,category,format,publishedAt,readingTime,featured,externalVideoUrl,seo,\n  "image":image{...,"asset":asset->{_id,_ref,url}},\n  author->{name,"slug":slug.current,role,bio,"image":image{...,"asset":asset->{_id,_ref,url}}}\n}': ARTICLES_QUERY_RESULT;
    '*[_type == "article" && slug.current == $slug][0]{\n  _id,title,"slug":slug.current,excerpt,category,format,publishedAt,readingTime,featured,externalVideoUrl,body,tags,seo,\n  "image":image{...,"asset":asset->{_id,_ref,url}},\n  author->{name,"slug":slug.current,role,bio,"image":image{...,"asset":asset->{_id,_ref,url}}},\n  relatedService->{title,"slug":slug.current},\n  relatedArticles[]->{_id,title,"slug":slug.current,excerpt,category,format,publishedAt,\n    "image":image{...,"asset":asset->{_id,_ref,url}}}\n}': ARTICLE_QUERY_RESULT;
    '*[_type == "brand"] | order(order asc, title asc){\n  title,"slug":slug.current,type,description,href,external,ctaLabel,order,\n  "image":image{...,"asset":asset->{_id,_ref,url}}\n}': BRANDS_QUERY_RESULT;
    '*[_type == "toolkit"] | order(order asc, title asc){\n  title,"slug":slug.current,type,description,access,coverStyle,externalUrl,\n  "fileUrl":downloadFile.asset->url,\n  "coverImage":coverImage{...,"asset":asset->{_id,_ref,url}}\n}': TOOLKITS_QUERY_RESULT;
    '*[_type == "founder"][0]{\n  name,headline,intro,body,belief,stats,statsNote,publications,roles,seo,\n  "image":image{...,"asset":asset->{_id,_ref,url}}\n}': FOUNDER_QUERY_RESULT;
    '*[_type == "mediaDesk"][0]{headline,intro,requestTypes,futureResources,seo}': MEDIA_DESK_QUERY_RESULT;
    '*[_type == "mediaHubPage"][0]{heroTitle,heroAccent,intro,ctaEyebrow,ctaHeading,ctaText,ctaButtonLabel,ctaButtonHref,seo}': MEDIA_HUB_QUERY_RESULT;
    '*[_type == "videoPage"][0]{heroTitle,heroAccent,intro,ctaEyebrow,ctaHeading,ctaText,ctaButtonLabel,ctaButtonHref,seo}': VIDEO_PAGE_QUERY_RESULT;
    '*[_type == "navigation"][0]{\n  about{eyebrow, heading, text, ctaLabel, ctaHref, links[]{label, page, externalUrl, service->{title, "slug": slug.current}}},\n  services{eyebrow, heading, text, ctaLabel, ctaHref, links[]{label, page, externalUrl, service->{title, "slug": slug.current}}}\n}': NAVIGATION_QUERY_RESULT;
    '*[_type == "videoGallery"] | order(coalesce(order, 999) asc, title asc){\n  title, "slug": slug.current, category, intro, order,\n  "poster": poster{..., "asset": asset->{_id,_ref,url}},\n  videos[]{heading, url, caption}\n}': VIDEOS_QUERY_RESULT;
    '*[_type == "videoGallery" && slug.current == $slug][0]{\n  title, "slug": slug.current, category, intro, order,\n  "poster": poster{..., "asset": asset->{_id,_ref,url}},\n  videos[]{heading, url, caption}, seo\n}': VIDEO_QUERY_RESULT;
    '*[_type == "diamondAwards"][0]{\n  eventName,date,venue,location,history,mission,missionPoints,audience,eventExperience,sponsorBenefits,\n  sponsorshipPackages,contactEmail,contactPhoneUae,contactPhoneUk,seo,\n  "heroImage":heroImage{...,"asset":asset->{_id,_ref,url}},\n  "historyImage":historyImage{...,"asset":asset->{_id,_ref,url}},\n  "missionImage":missionImage{...,"asset":asset->{_id,_ref,url}},\n  "whyDubaiImage":whyDubaiImage{...,"asset":asset->{_id,_ref,url}},\n  "sponsorImage":sponsorImage{...,"asset":asset->{_id,_ref,url}},\n  "experienceImage":experienceImage{...,"asset":asset->{_id,_ref,url}},\n  "contactImage":contactImage{...,"asset":asset->{_id,_ref,url}}\n}': DIAMOND_AWARDS_QUERY_RESULT;
  }
}
